# Generated by Django 3.1.4 on 2021-05-26 08:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210327_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=cloudinary.models.CloudinaryField(default='default.jpg', max_length=255),
        ),
    ]
