# Generated by Django 3.1.4 on 2021-05-26 08:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizzer',
            name='bg_pic',
            field=cloudinary.models.CloudinaryField(default='def.png', max_length=255),
        ),
    ]
