# Generated by Django 3.1.4 on 2021-04-24 19:11

from django.db import migrations, models
import quiz.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='points',
            field=models.PositiveIntegerField(default=1, verbose_name='points'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='answer',
            field=models.PositiveIntegerField(default=1, validators=[quiz.models.validate_ans], verbose_name='correct option'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='questions',
            name='slug',
            field=models.SlugField(blank=True, max_length=60, null=True),
        ),
    ]
