# Generated by Django 3.1.4 on 2021-03-08 16:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='content',
            new_name='option_1',
        ),
        migrations.AddField(
            model_name='questions',
            name='answer',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AddField(
            model_name='questions',
            name='option_2',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='questions',
            name='option_3',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='questions',
            name='option_4',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='questions',
            name='question',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='questions',
            name='quizz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quizzer'),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
