# Generated by Django 3.1.4 on 2021-03-13 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0002_auto_20210308_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='quizz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizz_question', to='quiz.quizzer'),
        ),
        migrations.AlterField(
            model_name='quizzer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_quiz', to=settings.AUTH_USER_MODEL),
        ),
    ]
