# Generated by Django 3.1.4 on 2021-03-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_quizzer_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizzer',
            name='bg_pic',
            field=models.ImageField(default='media/def.png', upload_to='quiz_pic'),
        ),
    ]
