# Generated by Django 3.1.4 on 2021-03-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_quizzer_bg_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizzer',
            name='bg_pic',
            field=models.ImageField(default='def.png', upload_to='quiz_pic'),
        ),
    ]
