# Generated by Django 3.1.4 on 2021-03-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_quizscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizzer',
            name='title',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
