# Generated by Django 3.1.4 on 2021-04-01 14:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_quizzer_reattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='answer',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='correct option'),
        ),
        migrations.AlterField(
            model_name='quizzer',
            name='reattempt',
            field=models.BooleanField(default=True, verbose_name='Allow Reattempt'),
        ),
    ]
