# Generated by Django 3.1.4 on 2021-04-06 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_auto_20210401_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizzer',
            name='private',
            field=models.BooleanField(default=False, verbose_name='Make private'),
        ),
    ]
