# Generated by Django 3.1.4 on 2021-04-12 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_usertags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTags',
        ),
    ]
